name: ${project.artifactId}
main: ${package}.${project.artifactId}
version: ${project.version}
author: ${developer}

commands:
   ${project.artifactId}:
      description: Manage ${project.artifactId}
   scheduler:
      description: Basic Scheduler Command
      usage: /scheduler [save/reload]
      permission: scheduler.manage
      permission-message: You don't have scheduler.manage
      aliases: schr 
